name: Auto-Approve PR

on:
  pull_request:
    types:
      - opened  # Trigger on new PRs

jobs:
  auto-approve:
    runs-on: ubuntu-latest

    steps:
      - name: Auto-Approve PR
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
